### PR TITLE
Fix tooltips on mobile filter sheet

### LINKED ISSUE #164: Filter clear hint is visible when opening the mobile filter sheet
When opening the mobile filter sheet, the hint for the first clear filter is always visible and has to be dismissed manually.

Expected: No hints are visible when opening the filter sheet

### PR DESCRIPTION
**Pull request by lfranke42**
Fixes #164 

- the upmost tooltip is no longer initially opened when opening the mobile search filter sheet
- added mobile functionality for tooltips since this is not natively supported by shadcn: https://github.com/shadcn-ui/ui/issues/86#issuecomment-2241817826
- fixed skeleton scaling issues on smaller screens

### CODE REVIEW

File: src/components/ui/tooltip.tsx [hunk 1]
```diff
@@ -16,10 +15,41 @@ function TooltipProvider({
...
+    children,
+    useTouch = true,
+    ...props
+}: React.ComponentProps<typeof TooltipPrimitive.Root> & {
+    useTouch?: boolean;
+}) {
+    const [open, setOpen] = React.useState(false);
+
+    const handleTouch = (event: React.TouchEvent | React.MouseEvent) => {
+        event.persist();
```
Comment (BauZee) [inline src/components/ui/tooltip.tsx]: I wanted to look up what it is and read that `event.persist()` is redundant from React 17 onwards. It can therefore be removed.

File: src/components/ui/tooltip.tsx [hunk 2]
```diff
@@ -16,10 +15,41 @@ function TooltipProvider({
...
+                onOpenChange={setOpen}
+                {...props}
+            >
+                {React.Children.map(children, (child) => {
+                    if (React.isValidElement(child) && useTouch) {
+                        return React.cloneElement(
+                            child as React.ReactElement<React.HTMLAttributes<HTMLElement>>,
+                            {
+                                onTouchStart: handleTouch,
+                                onMouseDown: handleTouch,
```
Comment (BauZee) [inline src/components/ui/tooltip.tsx]: Why should a tooltip be displayed when you click on it with the mouse? You should only need to hover the mouse over it for it to appear. It makes sense on a mobile phone, where you should click to see it.

File: src/components/ui/tooltip.tsx (hunk 1 above)
Comment (lfranke42) [reply src/components/ui/tooltip.tsx]: Yes, this was just a copy-pasta from the referenced issue. I didn't check that closely. Removed now

File: src/components/ui/tooltip.tsx [hunk 3]
```diff
@@ -16,10 +15,41 @@ function TooltipProvider({
...
+function Tooltip({
+    children,
+    useTouch = true,
+    ...props
+}: React.ComponentProps<typeof TooltipPrimitive.Root> & {
+    useTouch?: boolean;
+}) {
+    const [open, setOpen] = React.useState(false);
+
+    const handleTouch = (event: React.TouchEvent | React.MouseEvent) => {
```
[the remark this answers is not in the document]
Comment (lfranke42) [reply src/components/ui/tooltip.tsx]: removed
