### PR TITLE
#507 Fix safari issues

### LINKED ISSUE #506: Landing-Page unintentionally overlayed on Mobile
Logo is overlaying info-badge in hero.

- iOS 16
- iPhone 8 Plus
- Safari

Image

### PR DESCRIPTION
**Pull request by lfranke42**
fixes #506 #507

### CODE REVIEW

**Review by bruderj15 — COMMENTED** [review]
Confirming that landing-page logo and category-page cards are fixed now on my device

File: src/hooks/watchlist/useWatchlistNotificationMutation.ts [hunk 1]
```diff
@@ -2,15 +2,20 @@ import { useMutation, useQueryClient } from "@tanstack/react-query";
...
 import { useApiError } from "@/hooks/common/useApiError.ts";
 import { mapToInternalApiError } from "@/data/internal/hooks/ApiError.ts";
 import { parseLanguage } from "@/data/internal/common/Language.ts";
+import { useParams } from "@tanstack/react-router";
 
 export function useWatchlistNotificationMutation(shopId: string, shopsProductId: string) {
     const queryClient = useQueryClient();
     const { getErrorMessage } = useApiError();
 
+    const routeParams = useParams({ strict: false, shouldThrow: false });
```
Comment (lfranke42) [inline src/hooks/watchlist/useWatchlistNotificationMutation.ts:18]: Not 100% happy with this. Ideally we would pass slug/productId to the mutation itself, but we don't always have it. 
Making them optional props would be hacky as well since we then either have regular ID or slug ID. Having only slug ID then prevents us from invalidating other queries properly....

Maybe we should even drop the old getProduct enpoints entirely. Don't see a reason to keep supporting them, since we don't have any old links that need to still work.

Comment (bruderj15) [reply src/hooks/watchlist/useWatchlistNotificationMutation.ts:18]: I don't quite understand it. Does this look like a backend design-flaw for you?

Comment (lfranke42) [reply src/hooks/watchlist/useWatchlistNotificationMutation.ts:18]: No, probably more of a quirk on our side. Will have to look at this with fresh eyes tomorrow

Comment (lfranke42) [reply src/hooks/watchlist/useWatchlistNotificationMutation.ts:18]: Ahh should be fine for now

**Review by bruderj15 — APPROVED** [review]
